[package]
name = "wasmedge-pickledb-rs"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[lib]
name = "wasmedge_pickledb_rs"
path = "src/lib.rs"
crate-type =["cdylib"]

[dependencies]
pickledb = { git = "https://github.com/second-state/pickledb-rs" }
wasm-bindgen = "=0.2.61"
